import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Doctor Appointment Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className=" md:px-20">
        <Header/>
        {children}
      </div>
        </body>
    </html>
  );
}
